### ISSUE TITLE
Spring cloud kuberentes watcher spring boot 3.x help required

### ISSUE THREAD

**Issue by ryanjbaxter** [ryanjbaxter/demo-bot-repo#2]
Hi,
I'm trying to implement spring cloud kubernetes in our projects. My main goals are to read configMap, secrets and enable reload using spring cloud kubernetes config watcher.

Since there are very less examples available about how to use spring cloud for kubernetes apps, I read the documentation and figured out how to read secrets and configmap from k8s. There are 2 ways you can read these i.e

Volume mount
Kubernetes API
The 2nd one is not recommended due to security problems which can occur so I'm preferring 1st one. But when it comes to reloading properties using watcher then there is zero examples available with spring boot 3.x.

While using below properties in bootstrap.properties I get below warning logs
bootstrap.properties
spring.cloud.kubernetes.discovery.enabled=false spring.cloud.kubernetes.secrets.paths=/etc/secrets/secret-k8s spring.cloud.kubernetes.secrets.fail-fast=true spring.cloud.kubernetes.secrets.enabled=true

warning log
o.s.c.k.c.c.SecretsPropertySourceLocator : path support is deprecated and will be removed in a future release. Please use **spring.config.import**

But I couldn't find any help about how to use this property with kubernetes using volume mounts.

second thing is if possible could you please share an example of watcher with spring boot 3.x which should update mounted volume(secret/configmap) ?

build.gradle
dependencies { implementation 'org.springframework.boot:spring-boot-starter-actuator' implementation 'org.springframework.boot:spring-boot-starter-web' implementation group: 'org.springframework.cloud', name: 'spring-cloud-starter-kubernetes-fabric8-config', version: '3.0.4' compileOnly 'org.projectlombok:lombok' annotationProcessor 'org.projectlombok:lombok' testImplementation 'org.springframework.boot:spring-boot-starter-test' }

**Comment by ryanjbaxter** [comment]
To read ConfigMap and Secrets using volume mounts in Spring Cloud Kubernetes, you can follow these steps:

1. Create a ConfigMap and Secret in your Kubernetes cluster.

2. Mount the ConfigMap and Secret to a specific path in your Spring Boot application's deployment configuration.

3. Configure your Spring Boot application to read the properties from the mounted files using the `spring.config.import` property.

Here's an example of how you can achieve this:

1. Create a ConfigMap and Secret in your Kubernetes cluster:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  my.property: value

apiVersion: v1
kind: Secret
metadata:
  name: my-secret
data:
  my.secret.property: dmFsdWU=
```

2. Mount the ConfigMap and Secret to a specific path in your Spring Boot application's deployment configuration:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  template:
    spec:
      containers:
        - name: my-app
          image: my-app:latest
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
            - name: secret-volume
              mountPath: /etc/secrets
      volumes:
        - name: config-volume
          configMap:
            name: my-config
        - name: secret-volume
          secret:
            secretName: my-secret
```

3. Configure your Spring Boot application to read the properties from the mounted files using the `spring.config.import` property:
```
spring.config.import=file:/etc/config/application.properties,file:/etc/secrets/application-secrets.properties
```

Regarding the warning log you mentioned, the `spring.cloud.kubernetes.secrets.paths` property is deprecated in Spring Cloud Kubernetes 3.x. You should use the `spring.config.import` property instead, as mentioned in the warning log. The `spring.config.import` property allows you to specify multiple configuration files to import.

As for an example of using the Spring Cloud Kubernetes Config Watcher with Spring Boot 3.x, unfortunately, I couldn't find any specific examples for Spring Boot 3.x. However, you can refer to the official Spring Cloud Kubernetes documentation for more information on how to use the Config Watcher feature with Spring Cloud Kubernetes: https://cloud.spring.io/spring-cloud-kubernetes/reference/html/index.html
